name: clone_hotels
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.15.3
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.14
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  geolocator: ^10.1.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  nb_utils: ^6.1.2
  syncfusion_flutter_datepicker: ^24.1.47

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets: 
  - assets/
  - .env
