const imageOne = "assets/one.jpg";
const imageTwo = "assets/two.jpg";
const imageThree = "assets/three.jpg";
const beach = "assets/beach.jpg";
const firstRoom = "assets/first_room.jpg";
const secondRoom = "assets/second_room.jpg";
const thirdRoom = "assets/third_room.jpg";
List<String> imagesToFOS = [imageOne, imageTwo, imageThree];
List<String> imagesToRoomsList = [firstRoom, secondRoom, thirdRoom];